(deftheme MinimalistTheme
  "Created 2020-06-21.")

(custom-theme-set-faces
 'MinimalistTheme
 '(default ((t (:inherit nil :stipple nil :background "#000000" :foreground "#FFFFFF" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 110 :width normal :foundry "PfEd" :family "DejaVu Sans Mono"))))
 '(cursor ((t (:background "#FFFFFF" :foreground "#000000"))))
 '(fixed-pitch ((t (:family "DejaVu Sans Mono" :foundry "PfEd" :width normal :height 110 :weight normal :slant normal))))
 '(variable-pitch ((t (:family "DejaVu Sans" :foundry "PfEd" :width normal :height 110 :weight normal :slant normal))))
 '(escape-glyph ((t (:foreground "gainsboro"))))
 '(homoglyph ((t (:foreground "gray"))))
 '(minibuffer-prompt ((t (:foreground "gray"))))
 '(highlight ((t (:background "#000000" :foreground "#FFFFFF"))))
 '(region ((t (:background "#42444a"))))
 '(shadow ((t (:foreground "#5B6268"))))
 '(secondary-selection ((t (:background "#3f444a"))))
 '(trailing-whitespace ((t (:background "#ff6c6b"))))
 '(font-lock-builtin-face ((t (:foreground "#FFFFFF"))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#5B6268"))))
 '(font-lock-constant-face ((t (:foreground "#FFFFFF"))))
 '(font-lock-doc-face ((t (:foreground "#83898d" :inherit (font-lock-comment-face)))))
 '(font-lock-function-name-face ((t (:foreground "#FFFFFF"))))
 '(font-lock-keyword-face ((t (:foreground "gainsboro"))))
 '(font-lock-negation-char-face ((t (:inherit bold :foreground "gainsboro"))))
 '(font-lock-preprocessor-face ((t (:inherit bold :foreground "gainsboro"))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit bold :foreground "gainsboro"))))
 '(font-lock-regexp-grouping-construct ((t (:inherit bold :foreground "gainsboro"))))
 '(font-lock-string-face ((t (:foreground "white smoke"))))
 '(font-lock-type-face ((t (:foreground "white smoke"))))
 '(font-lock-variable-name-face ((t (:foreground "white smoke"))))
 '(font-lock-warning-face ((t (:inherit (warning)))))
 '(button ((t (:foreground "#FFFFFF"))))
 '(link ((t (:foreground "#FFFFFF" :underline t :weight bold))))
 '(link-visited ((t (:inherit link :foreground "gray"))))
 '(fringe ((t (:foreground "#3f444a" :inherit (default)))))
 '(header-line ((t (:foreground "#bbc2cf" :background "#282c34"))))
 '(tooltip ((t (:foreground "#bbc2cf" :background "#23272e"))))
 '(mode-line ((t (:box nil :foreground "#bbc2cf" :background "#1c1e24"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:foreground "#FFFFFF"))))
 '(mode-line-highlight ((t (:inherit highlight :background "#FFFFFF" :foreground "#000000"))))
 '(mode-line-inactive ((t (:box nil :foreground "#5B6268" :background "#1d2026"))))
 '(isearch ((t (:inherit lazy-highlight :background "#FFFFFF" :foreground "#000000" :weight bold))))
 '(isearch-fail ((t (:weight bold :foreground "#1B2229" :background "#ff6c6b"))))
 '(lazy-highlight ((t (:background "#FFFFFF" :foreground "#000000" :weight bold))))
 '(match ((t (:background "#FFFFFF" :foreground "#000000" :weight bold))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit isearch :background "#FFFFFF" :foreground "#000000")))))

(provide-theme 'MinimalistTheme)
